# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Jeremiah Cupery
title: Technical Specialist - Aerosol Filtration Research
email: jcupery@hotmail.com
website: jcupery.github.io

# Social links
#twitter_username: facespics
github_username:  jcupery
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: jcupery
# pinterest_username: jekyll
youtube_username: jcupery
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/jcupery.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Jeremiah and I'm an engine guy. As well as intake air filtraiton research, I also have experience in engine design and analysis. I have worked at a number of companies in the automotive and engine industry which has given me a broad understanding of different engine platforms and types.

  I am most skilled in: <mark>CAD Design</mark> and <mark>Analysis</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in engineering and internal combustion engines some of my other interests and hobbies are:
   - Car modification, restoration, and motorsports
   - Playing guitar and music recording
   - Biking and snowboarding
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
